# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               jseptienr
tagline:             'Quantum Thoughts'
description:         'My personal github blog on random topics.'
url:                 http://jseptienr.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              JSeptien
  url:               https://twitter.com/jseptienr
  email:             

# Custom vars
version:             1.0.0
